version: '2'
services:
  mongodb:
    image: mongo
    ports:
    - 28017:28017
    - 27017:27017
  mongo_seed:
    build: ./mongo-gas-stations
    links:
    - mongodb
  mysql:
    build: ./prices-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gas_prices_db
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
      - "8300:8300"
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  grafana:
    ports:
    - "3000:3000"
    volumes:
    - /var/lib/grafana
    links:
    - prometheus
    image: grafana/grafana
  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    image: prom/prometheus