micronaut:
  application:
    name: prices
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1
endpoints:
  metrics:
    enabled: false
  prometheus:
    enabled: true
db:
  uri: jdbc:mysql://localhost:3306/gas_prices_db?allowPublicKeyRetrieval=true&user=root&password=admin&useSSL=false